### ISSUE TITLE
is there any tutorial？

### ISSUE THREAD

**Issue by azureskyL** [NonameAuPlatal/Dual_Learning#1]
It's not ready for use. There are many bugs. I will write the tutorial when it's finished.

**Comment by NonameAuPlatal** [comment]
It's not ready for use. There are many bugs. I will write the tutorial when it's finished.

**Comment by azureskyL** [comment]
I'm interesting in Dual Learning and expect you to finish this project as soon as possible : )

**Comment by qmpham** [comment]
I think the code is good now. You can ask me directly if you have troubles.

**Comment by BattsetsegB** [comment]
is there any tutorial？ i trained language model and translation model,but don't know how to train bilingual word embeddings for 2 languages.help me!

**Comment by qmpham** [comment]
To train bilingual word embedding, I suggest you to use https://github.com/facebookresearch/MUSE
By the way, I will write more details on the tutorial. Very sorry about the incomprehensibility of the tutorial

**Comment by BattsetsegB** [comment]
thank you for your reply in time! i want implement  DL4MT on small corpora , same as you. but can't find other comprehensibility tutorial.

**Comment by qmpham** [comment]
Yeah, I think that now there is not any implementation of DL4MT using Theano because Theano is no longer maintained, but you can try Nematus Tensorflow (before it was written in Theano) https://github.com/EdinburghNLP/nematus

**Comment by BattsetsegB** [comment]
thanks for advance , I will try it. And expect you to write more details on this project(Dual_learning).

**Comment by BattsetsegB** [comment]
hey, i have pretrained lm and translation model of fr<==>en ,i put them /models directory, to train Dual_training1.py code.   Is it possible? 

path_trans_en_fr = home_dir + "Dual_NMT/models/NMT/lowercased/model_en_fr.npz.npz.best_bleu",
              path_trans_fr_en = home_dir + "Dual_NMT/models/NMT/lowercased/model_fr_en.npz.npz.best_bleu",
              path_mono_en = home_dir + "Dual_NMT/models/LM/lowercased/model_lm_en.npz",
              path_mono_fr = home_dir + "Dual_NMT/models/LM/lowercased/model_lm_fr.npz",

**Comment by qmpham** [comment]
I think it's ok. You have to assign correct directory to path_trans_en_fr, path_trans_fr_en, path_mono_en, path_mono_fr

**Comment by qmpham** [comment]
It's not really comfortable for you guys, because my code is made for very old version nematus. I will write another version for recent NMT models (tensorflow or pytorch) if I have time.

**Comment by BattsetsegB** [comment]
sorry, it's me again. i assigned correct directory lm and nmt models, run dual_learning.py. but 
$ THEANO_FLAGS='mode=FAST_RUN,floatX=float32,device=cuda0,blas.ldflags=-lblas' python Dual_training_1.py
Using cuDNN version 6021 on context None
Mapped name None to device cuda0: GeForce GTX 960 (0000:01:00.0)
Traceback (most recent call last):
  File "Dual_training_1.py", line 5, in <module>
    import theano.sandbox.gpuarray
ImportError: No module named gpuarray

i use conda to install theano pygpu, tested ok.
DEVICE="cuda" python -c "import pygpu;pygpu.test()"
******************************************************************
Ran 7301 tests in 126.844s
OK

Also change theano.sandbox.gpuarray to theano.gpuarray, no error but couldn't train.
babi@Lenovo:~/Dual_Learning$ THEANO_FLAGS='mode=FAST_RUN,floatX=float32,device=cuda0,blas.ldflags=-lblas' python Dual_training_1.py
Using cuDNN version 6021 on context None
Mapped name None to device cuda0: GeForce GTX 960 (0000:01:00.0)
babi@Lenovo:~/Dual_Learning$ 
what should i do?

**Comment by qmpham** [comment]
There is not any error at all? Can I see you log?

**Comment by BattsetsegB** [comment]
Hi, First I assigned correct directory lm and nmt models, then run dual_learning.py. but appears this error.
Traceback (most recent call last):
File "Dual_training_1.py", line 5, in
import theano.sandbox.gpuarray
ImportError: No module named gpuarray

Then I changed **theano.sandbox.gpuarray** of "Dual_training_1.py", line 5 to **theano.gpuarray**, run it. but there isn't any error, Terminal like this.

babi@Lenovo:/Dual_Learning$ THEANO_FLAGS='mode=FAST_RUN,floatX=float32, device=cuda0, blas.ldflags=-lblas' python Dual_training_1.py
Using cuDNN version 6021 on context None
Mapped name None to device cuda0: GeForce GTX 960 (0000:01:00.0)
babi@Lenovo:/Dual_Learning$

**Comment by qmpham** [comment]
Does the training stop?

**Comment by BattsetsegB** [comment]
yes, there is not error, no train.

**Comment by 0uO** [comment]
Maybe it is the problem of theano version, you could try version 0.8.0 and corresponding pygpu. (It is just a guess. I haven't run the code still.)

**Comment by BattsetsegB** [comment]
version 0.8.0 no difference , but I modify sample_config.py , then run it.It nearly success, but appears error.I have attached my log: 
[output_log.txt](https://github.com/NonameAuPlatal/Dual_Learning/files/2592762/output_log.txt)
any advance guys?
